### ISSUE TITLE
Plausible for analytics?

### ISSUE THREAD

**Issue by drmowinckels** [rladies/website#105]
Do we want to have some basic idea of website usage? Could be good to have for funding reports etc?
We dont want to use google analytics (I assume), so we could for instance try [Matomo](https://matomo.org/) like rOpenSci does?

**Comment by Athanasiamo** [comment]
I sent an email for discount estimate.

**Comment by Athanasiamo** [comment]
We're going for plausible in stead! 

https://plausible.io/
