### ISSUE TITLE
getting events trough CI

### ISSUE THREAD

**Issue by Athanasiamo** [rladies/website#11]
Currently, updates of events information must be done interactively, since we have not managed to setup meetupr to work in CIs. For the events page to work as wanted, we need to fix meetupr to work with a CI, so we can create a workflow here that grabs events data on regular intervals (preferably through github actions).

**Comment by maelle** [comment]
why doesn't meetupr work with a CI btw? Because we couldn't save the OAuth stuff?

**Comment by Athanasiamo** [comment]
Because we currently have not set the package up to be able to handle non-interactive OAuth. 
I was trying to figure it out, but I just dont understand OAuth processes well enough to get it working.

https://github.com/rladies/meetupr/issues/65

**Comment by Athanasiamo** [comment]
fxed in commit [52500bc81](https://github.com/rladies/website/commit/52500bc8189b28a31d8f76df7ab7826490d58a31)
