### ISSUE TITLE
Broken fullcalendar 

### ISSUE THREAD

**Issue by drmowinckels** [rladies/website#114]
Sorry, @benubah in the [news branch](https://github.com/rladies/website/tree/news) I did some simplification of the theme layouts to make sure things looked the same across different pages (titles etc were off). 

In that work, I somehow managed to break the Fullcalendar. Its there, but it looks totally crazy (especially month view). If you have the time to take a look at what I did, I'll appreciate that.

Thanks

**Comment by drmowinckels** [comment]
You can see the preview version here: https://6374b5e912e31e3a00ce32d4--rladies-dev.netlify.app/activities/events/

**Comment by benubah** [comment]
thanks! On this now

**Comment by benubah** [comment]
@drmowinckels Does this work? https://github.com/rladies/website/pull/117
