### ISSUE TITLE
translated pages not working well

### ISSUE THREAD

**Issue by Athanasiamo** [rladies/website#13]
I think I have not setup the theme or maybe the content (I'm not sure) to work well with translated pages. 
Currently, when trying to access translated pages through the footer, most pages are empty (because most pages are not translated).

**Comment by maelle** [comment]
so even the links to actually translated pages are broken?

**Comment by Athanasiamo** [comment]
Well, the only translations at the moment is the CoC (not ideally set up, but we'll get there). And there it works just fine.
But once on the Spanish CoC page, pressing any other internal link (like menu) on the page directs you to a blank page. 

I thought hugo would re-direct to the default language page in such instances, but I might either have misunderstood the docs or setup the translations wrong.

**Comment by maelle** [comment]
I'll have to read up on Hugo translation stuff.

**Comment by Athanasiamo** [comment]
I think this describes what I would have wanted, and an answer here describes possible solutions to what we are after (maybe linking to the default language content when a translation is missing)

https://discourse.gohugo.io/t/i18n-a-way-to-force-page-generation-even-if-it-isnt-translated/24438/3

**Comment by Athanasiamo** [comment]
I've implemented some translational things in the with_posts branch. 

The GH action is not set up yet, but I have a script that will generated site language md's for all the site pages without translations. They have a frontmatter key-value pair indicating that this md is not actually a translated version, and a message is displayed indicating this.

![Warning that page has not been translated](https://user-images.githubusercontent.com/14014329/105630051-e81f0200-5e46-11eb-973c-f11c4e075277.png)

This only goes for pages, not posts (But can be implemented there too if needed). 

This way, there are md's in place for translation for whomever can contribute this, and the frontmatter can be altered when the translation is complete.

**Comment by Athanasiamo** [comment]
forgot the fix tag on this. A gh action now adds the above for untranslated pages in the site languages right before build. These pages are never committed to history. 

For untranslated pages the SEO is optimized so that:
- despite vieweing the page, for instace, in Spanish. When viewing an untranslated Spanish page the content is in english, and so the page langage is set to English rather than spanish.
- all specific div's with content in another language than the declared page language as tagged with `lang` so that we dont loose SEO for mixed language contents.
