### ISSUE TITLE
Something breaks the page for the previews

### ISSUE THREAD

**Issue by Athanasiamo** [rladies/website#23]
There is something making the branch preview sites render oddly.
Images missing, menu items not being selectable, pages dissapearing. 

Dont know what is happening, but would love input.

Example:
branch: https://github.com/rladies/website/pull/22
renders: https://deploy-preview-22--pensive-babbage-969fad.netlify.app/directory/

Dont ever merge this branch, it is nonsensical.

**Comment by maelle** [comment]
interesting as the non selectable menu items seem to be random? looking now

**Comment by maelle** [comment]
well not random, the second item of both drop downs

**Comment by maelle** [comment]
reg the missing images that might be easier to fix, it reminds me of other issues.
