### ISSUE TITLE
should we integrate the blog one day?

### ISSUE THREAD

**Issue by maelle** [rladies/website#32]

**Comment by Athanasiamo** [comment]
One tricky part with blog integration, is that the blog currently requires blogdown for rendering it. So we'll need to setup some decent workflow for everyrone working on the blog to feel comfortable with it. Secondly, I'm wondering whether actually having the blog separate is good in terms of updating blog being less likely of unintendedly breaking something on the webpage? I'm leaning towards keeping them separate, but maybe having the theme shared between them? Not sure yet.

If we can create a workflow for updating the blog that works for everyone, integrating would for sure be the cleanest long-term solution.

**Comment by maelle** [comment]
I'm actually wondering whether we really need blogdown for the blog as we rarely  have R code?
At least it'd be nice to share the same theme, especially the navbar and footer. :thinking:

**Comment by Athanasiamo** [comment]
I agree, ideally, I think we should switch to a similar type of setup I use for my blog (I am biased here though). 

A couple of things I think would make the blog easier to maintain over time:
1. start creating page bundles (I can bundle the old posts)
   - creates a neater file structure
   - easier for contributers to add images and auxillary files directy in the bundle
2. locally knitting Rmd to md, ignoring htmls in the git commits.
  -This way, we are not bound to keep the few Rmds we have perpetually updated and make sure they will forever knit
  - Reduce time from a new post is committed to its on the blog (currently installing all of tidyverse and taking quite some time doing so and re-knitting all posts, for every new post)
  - Reduce software dependencies that might break (R, blogdown, and any packages used in posts)
  
  If we decide on doing something like this, I also would suggest that all post-folders are prefixed with the date. This will just make it easier for finding easily in the content folder what is the newest post. But that is a personal preferance. (all of this is :P)

**Comment by maelle** [comment]
The new blogdown even has a function for bundling old posts and has "markdown" was the build method 😀

I unsurprisingly agree with all your points!

**Comment by Athanasiamo** [comment]
If we want to intregrate, and keep git histories of both, we'll need to to an unrelated history merge.

https://reactgo.com/git-merge-unrelated-histories/

**Comment by Athanasiamo** [comment]
Here's a preview of how integrating could look like. I merged the git histories yesterday successfully.

branch: https://github.com/rladies/website/tree/with_posts
preview: https://6009fd5d63d8b50007f413a9--pensive-babbage-969fad.netlify.app/

Go to `posts` rather than `blog`

Downside now is that there is no blogdown workflow for the config-directory that we are using on the webpage. Its coming, but not there yet.

**Comment by Athanasiamo** [comment]
Blog integration is merged from #40 . New posts coming after this should be easy to add as git histories are kept.
