### ISSUE TITLE
less details about wearerladies beyond the mission and Twitter account?

### ISSUE THREAD

**Issue by maelle** [rladies/website#34]
and link to https://guide.rladies.org/rocur/?

**Comment by Athanasiamo** [comment]
I was wondering if many of the "Activities" actually could be under a single page with separate headers, rather than on separate pages? Since much information is in the guide, we "just" want a general introduction to them, maybe?

**Comment by maelle** [comment]
Sounds good but then "Events" should be its own header between directory and activities?

**Comment by Athanasiamo** [comment]
Yes, I think thats what I had planned in my head without being so explicit :D
