### ISSUE TITLE
Directory images

### ISSUE THREAD

**Issue by drmowinckels** [rladies/website#87]
How do we deal with directory images? Currently they are hosted through wordpress, but these will go away once we dicontinue the WP site.

images in a git repo may inflate the repo quickly, but I dont know any other way to go about it?

Suggestions welcome.

**Comment by Athanasiamo** [comment]
we have the directory repo, we could have them there? I'm planning on that repo fairly regularly having changes to the git history anyway (need to figure out some technicalities there). But ideally, I'd want all previous history of a directory entry to be purged upon edit and deletion anyway, so storing images there should not particularly inflate git over time.

**Comment by maelle** [comment]
Yeah and the repo could be private but with a folder deployed on Netlify? So the git history would remain private?
