### ISSUE TITLE
directory nav arrows not working

### ISSUE THREAD

**Issue by drmowinckels** [rladies/website#88]

**Comment by drmowinckels** [comment]
@benubah i've created a larger mock directory and decrease page size to 5 if in development mode. This should make it easier to figure out what the List.js paginator arrows are not doing as expected.

**Comment by benubah** [comment]
Many thanks!

**Comment by benubah** [comment]
Looking at this! Found the problem

**Comment by drmowinckels** [comment]
Great! Looking forward to the solution :)

**Comment by benubah** [comment]
Found  a solution
